"""UP models 24.7/10h

Revision ID: 01af09ed099b
Revises: 3a11462b9bdb
Create Date: 2025-07-24 10:55:05.037239

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '01af09ed099b'
down_revision = '3a11462b9bdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detalecoretreat',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalecoretreat')
    # ### end Alembic commands ###
