"""UP models 10.07

Revision ID: 030bec3bfe5f
Revises: 1738f2f23047
Create Date: 2025-07-10 10:48:32.991788

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '030bec3bfe5f'
down_revision = '1738f2f23047'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
