"""ud models 07.07

Revision ID: 04037f0820d6
Revises: 9c233166b19c
Create Date: 2025-07-07 11:18:28.434019

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '04037f0820d6'
down_revision = '9c233166b19c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_projectlist_name'), 'projectlist', ['name'], unique=False)
    op.create_index(op.f('ix_request_id'), 'request', ['id'], unique=False)
    op.create_index(op.f('ix_request_project_id'), 'request', ['project_id'], unique=False)
    op.create_index(op.f('ix_request_requester_id'), 'request', ['requester_id'], unique=False)
    op.create_index(op.f('ix_request_role_id'), 'request', ['role_id'], unique=False)
    op.drop_index(op.f('ix_role_name'), table_name='role')
    op.create_index(op.f('ix_role_name'), 'role', ['name'], unique=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'creation_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.alter_column('user', 'creation_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_index(op.f('ix_role_name'), table_name='role')
    op.create_index(op.f('ix_role_name'), 'role', ['name'], unique=False)
    op.drop_index(op.f('ix_request_role_id'), table_name='request')
    op.drop_index(op.f('ix_request_requester_id'), table_name='request')
    op.drop_index(op.f('ix_request_project_id'), table_name='request')
    op.drop_index(op.f('ix_request_id'), table_name='request')
    op.drop_index(op.f('ix_projectlist_name'), table_name='projectlist')
    # ### end Alembic commands ###
