"""UP models 11.07/17h

Revision ID: 0461bc2c354d
Revises: 36daf7e97c35
Create Date: 2025-07-11 17:14:04.376199

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0461bc2c354d'
down_revision = '36daf7e97c35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ecopark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('picture_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('building_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('building_type_en', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('amenity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('amenity_type_en', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('zone_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('zone_name_en', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('zone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('amenity', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('direction', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bedroom', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('direction_en', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status_en', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projectlist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ecopark')
    # ### end Alembic commands ###
