"""fix models 07.07

Revision ID: 051bb31e0ea6
Revises: 0ac7693427bd
Create Date: 2025-07-07 10:46:21.060722

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '051bb31e0ea6'
down_revision = '0ac7693427bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
