"""UP models 25/8

Revision ID: 0bb88a9e8ec4
Revises: ce6238fc635e
Create Date: 2025-08-25 10:02:43.057556

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0bb88a9e8ec4'
down_revision = 'ce6238fc635e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
