"""UP models 4/8

Revision ID: 0f14c4b74e62
Revises: 6d96831cc377
Create Date: 2025-08-04 09:20:28.037030

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0f14c4b74e62'
down_revision = '6d96831cc377'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrativeregionlist',
    sa.Column('name_vi', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('name_en', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('code_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code_name_en', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('administrativeunitlist',
    sa.Column('full_name_vi', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('full_name_en', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('short_name_vi', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('short_name_en', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code_name_en', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provincelist',
    sa.Column('name_vi', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('name_en', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('full_name_vi', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('full_name_en', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('administrative_unit_id', sa.Integer(), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.ForeignKeyConstraint(['administrative_unit_id'], ['administrativeunitlist.id'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('wardlist',
    sa.Column('name_vi', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('name_en', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('full_name_vi', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('full_name_en', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('code_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('province_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('administrative_unit_id', sa.Integer(), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.ForeignKeyConstraint(['administrative_unit_id'], ['administrativeunitlist.id'], ),
    sa.ForeignKeyConstraint(['province_code'], ['provincelist.code'], ),
    sa.PrimaryKeyConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wardlist')
    op.drop_table('provincelist')
    op.drop_table('administrativeunitlist')
    op.drop_table('administrativeregionlist')
    # ### end Alembic commands ###
