"""UP models 26.7/15h

Revision ID: 17b3a70c1e9e
Revises: 767f2117471b
Create Date: 2025-07-26 15:38:34.677645

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '17b3a70c1e9e'
down_revision = '767f2117471b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
