"""UP models 11.07

Revision ID: 1b44b59105c4
Revises: 030bec3bfe5f
Create Date: 2025-07-11 11:46:47.355332

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1b44b59105c4'
down_revision = '030bec3bfe5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('system_rank', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('system_role_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'user', 'system', ['system_role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'system_role_id')
    op.drop_table('system')
    # ### end Alembic commands ###
