"""UP models 3/9.09h

Revision ID: 234fc0c8f1ea
Revises: a97b4664c359
Create Date: 2025-09-03 09:34:40.671471

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '234fc0c8f1ea'
down_revision = 'a97b4664c359'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
