"""UP models 24.07

Revision ID: 3450471ba735
Revises: e0cf886b4ed0
Create Date: 2025-07-24 09:19:00.824857

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3450471ba735'
down_revision = 'e0cf886b4ed0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projectlist', sa.Column('name_vi', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('projectlist', sa.Column('name_en', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('projectlist', sa.Column('address_vi', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('projectlist', sa.Column('address_en', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('projectlist', sa.Column('type_vi', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('projectlist', sa.Column('type_en', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('projectlist', sa.Column('investor_vi', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('projectlist', sa.Column('investor_en', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('projectlist', 'investor')
    op.drop_column('projectlist', 'name')
    op.drop_column('projectlist', 'type')
    op.drop_column('projectlist', 'address')
    op.add_column('request', sa.Column('request_message_vi', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('request', sa.Column('request_message_en', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('request', sa.Column('response_message_vi', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('request', sa.Column('response_message_en', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('request', 'response_message')
    op.drop_column('request', 'request_message')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('request_message', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.add_column('request', sa.Column('response_message', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.drop_column('request', 'response_message_en')
    op.drop_column('request', 'response_message_vi')
    op.drop_column('request', 'request_message_en')
    op.drop_column('request', 'request_message_vi')
    op.add_column('projectlist', sa.Column('address', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('projectlist', sa.Column('type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('projectlist', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('projectlist', sa.Column('investor', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('projectlist', 'investor_en')
    op.drop_column('projectlist', 'investor_vi')
    op.drop_column('projectlist', 'type_en')
    op.drop_column('projectlist', 'type_vi')
    op.drop_column('projectlist', 'address_en')
    op.drop_column('projectlist', 'address_vi')
    op.drop_column('projectlist', 'name_en')
    op.drop_column('projectlist', 'name_vi')
    # ### end Alembic commands ###
