"""UP models 11.07/13h

Revision ID: 36daf7e97c35
Revises: 1b44b59105c4
Create Date: 2025-07-11 13:46:10.643235

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '36daf7e97c35'
down_revision = '1b44b59105c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system', sa.Column('rank_total', sa.Integer(), nullable=False))
    op.drop_column('system', 'system_rank')
    op.add_column('user', sa.Column('system_rank', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('user_system_role_id_fkey'), 'user', type_='foreignkey')
    op.drop_column('user', 'system_role_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('system_role_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('user_system_role_id_fkey'), 'user', 'system', ['system_role_id'], ['id'])
    op.drop_column('user', 'system_rank')
    op.add_column('system', sa.Column('system_rank', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('system', 'rank_total')
    # ### end Alembic commands ###
