"""UP models 24.7

Revision ID: 3a11462b9bdb
Revises: 3450471ba735
Create Date: 2025-07-24 09:45:20.808244

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3a11462b9bdb'
down_revision = '3450471ba735'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
