"""UP models 18.07

Revision ID: 41534ce97dcd
Revises: 8be34662c176
Create Date: 2025-07-18 10:42:32.697553

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '41534ce97dcd'
down_revision = '8be34662c176'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ecopark', sa.Column('building_type_vi', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ecopark', sa.Column('amenity_type_vi', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ecopark', sa.Column('zone_name_vi', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ecopark', sa.Column('direction_vi', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ecopark', sa.Column('status_vi', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('ecopark', 'amenity_type')
    op.drop_column('ecopark', 'zone_name')
    op.drop_column('ecopark', 'status')
    op.drop_column('ecopark', 'building_type')
    op.drop_column('ecopark', 'direction')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ecopark', sa.Column('direction', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ecopark', sa.Column('building_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ecopark', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ecopark', sa.Column('zone_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ecopark', sa.Column('amenity_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('ecopark', 'status_vi')
    op.drop_column('ecopark', 'direction_vi')
    op.drop_column('ecopark', 'zone_name_vi')
    op.drop_column('ecopark', 'amenity_type_vi')
    op.drop_column('ecopark', 'building_type_vi')
    # ### end Alembic commands ###
