"""UP models 24.7/11h

Revision ID: 4fa6cd20d79f
Revises: 01af09ed099b
Create Date: 2025-07-24 10:57:18.110614

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4fa6cd20d79f'
down_revision = '01af09ed099b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
