"""UP models 26.7/15.30h

Revision ID: 5bd6ae48ffcd
Revises: 97701aab83e0
Create Date: 2025-07-26 15:50:42.067721

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5bd6ae48ffcd'
down_revision = '97701aab83e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
