"""UP models 26.7/14.40h

Revision ID: 5bf81f33afdd
Revises: e5bf184bf0b0
Create Date: 2025-07-26 16:06:51.516868

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5bf81f33afdd'
down_revision = 'e5bf184bf0b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
