"""UP models 12/8

Revision ID: 6724e3993212
Revises: 0f14c4b74e62
Create Date: 2025-08-12 11:56:35.156172

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6724e3993212'
down_revision = '0f14c4b74e62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
