"""UP models 26.7/14.50h

Revision ID: 6d96831cc377
Revises: 5bf81f33afdd
Create Date: 2025-07-26 16:10:24.906667

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6d96831cc377'
down_revision = '5bf81f33afdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
