"""UP models 26.7/14h

Revision ID: 767f2117471b
Revises: 178e43514766
Create Date: 2025-07-26 13:44:48.866937

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '767f2117471b'
down_revision = '178e43514766'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('detalecoretreat', 'port',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ecopark', 'port',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ecopark', 'port',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('detalecoretreat', 'port',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
