"""UP models 30/8

Revision ID: 7a7d556bcaf1
Revises: 0bb88a9e8ec4
Create Date: 2025-08-30 10:51:15.454001

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7a7d556bcaf1'
down_revision = '0bb88a9e8ec4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system', 'name')
    # ### end Alembic commands ###
