"""UP models 07.07

Revision ID: 81b63089d054
Revises: c20ebcbd8ddb
Create Date: 2025-07-07 17:00:42.142369

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '81b63089d054'
down_revision = 'c20ebcbd8ddb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
