"""UP models 24.7/15h

Revision ID: 8769e962f301
Revises: 
Create Date: 2025-07-24 16:12:34.364869

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8769e962f301'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detalecoretreat',
    sa.Column('building', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('picture', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description_vi', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description_en', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projectlist',
    sa.Column('name_vi', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name_en', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address_vi', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address_en', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('type_vi', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('type_en', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('investor_vi', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('investor_en', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('picture', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rank_total', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('creation_time', sa.DateTime(), nullable=False),
    sa.Column('role_assignment_time', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('last_logout', sa.DateTime(), nullable=True),
    sa.Column('system_rank', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('ecopark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('picture_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('building_type_vi', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('building_type_en', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('amenity_type_vi', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('amenity_type_en', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('zone_name_vi', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('zone_name_en', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('zone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('amenity', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('direction_vi', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bedroom', sa.Integer(), nullable=True),
    sa.Column('price', sa.BigInteger(), nullable=True),
    sa.Column('status_vi', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('direction_en', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status_en', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description_vi', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description_en', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projectlist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('request',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('requester_id', sa.Uuid(), nullable=False),
    sa.Column('approver_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='requeststatus'), nullable=False),
    sa.Column('request_message_vi', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('request_message_en', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('response_message_vi', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('response_message_en', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projectlist.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_id'), 'request', ['id'], unique=False)
    op.create_index(op.f('ix_request_project_id'), 'request', ['project_id'], unique=False)
    op.create_index(op.f('ix_request_requester_id'), 'request', ['requester_id'], unique=False)
    op.create_index(op.f('ix_request_role_id'), 'request', ['role_id'], unique=False)
    op.create_table('userprojectrole',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projectlist.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'project_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userprojectrole')
    op.drop_index(op.f('ix_request_role_id'), table_name='request')
    op.drop_index(op.f('ix_request_requester_id'), table_name='request')
    op.drop_index(op.f('ix_request_project_id'), table_name='request')
    op.drop_index(op.f('ix_request_id'), table_name='request')
    op.drop_table('request')
    op.drop_table('ecopark')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('system')
    op.drop_table('role')
    op.drop_table('projectlist')
    op.drop_table('detalecoretreat')
    # ### end Alembic commands ###
