"""UP models 12.07/18h

Revision ID: 8be34662c176
Revises: 2715affc6939
Create Date: 2025-07-12 15:28:34.859984

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8be34662c176'
down_revision = '2715affc6939'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
