"""UP models 26.7/15.30h

Revision ID: 97701aab83e0
Revises: b7dc020ad788
Create Date: 2025-07-26 15:48:45.647262

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '97701aab83e0'
down_revision = 'b7dc020ad788'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
