"""UP models 3/9.08h

Revision ID: a97b4664c359
Revises: e69bfa9b3f58
Create Date: 2025-09-03 09:30:25.554338

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a97b4664c359'
down_revision = 'e69bfa9b3f58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
