"""UP models 26.7/15.30h

Revision ID: b7dc020ad788
Revises: 17b3a70c1e9e
Create Date: 2025-07-26 15:43:00.095700

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b7dc020ad788'
down_revision = '17b3a70c1e9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
