"""UP models 3/9.10h

Revision ID: b8a934e61dd5
Revises: 234fc0c8f1ea
Create Date: 2025-09-03 09:48:12.717471

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b8a934e61dd5'
down_revision = '234fc0c8f1ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
