"""UP models 10/9.10h

Revision ID: bb5ff0d4e0be
Revises: b8a934e61dd5
Create Date: 2025-09-10 14:20:04.738340

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'bb5ff0d4e0be'
down_revision = 'b8a934e61dd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
