"""UP models 14/8

Revision ID: be6c2fbdf96f
Revises: 6724e3993212
Create Date: 2025-08-14 11:06:46.186959

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'be6c2fbdf96f'
down_revision = '6724e3993212'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userprojectrole', sa.Column('id', sa.Uuid(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userprojectrole', 'id')
    # ### end Alembic commands ###
