"""N models 07.07

Revision ID: c20ebcbd8ddb
Revises: 04037f0820d6
Create Date: 2025-07-07 11:18:49.287695

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c20ebcbd8ddb'
down_revision = '04037f0820d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
