"""UP models 24.7/13h

Revision ID: c8cf3b91e5d3
Revises: f1bbf0d4600a
Create Date: 2025-07-24 11:24:39.472147

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c8cf3b91e5d3'
down_revision = 'f1bbf0d4600a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
