"""UP models 14/8.11

Revision ID: ce6238fc635e
Revises: be6c2fbdf96f
Create Date: 2025-08-14 11:20:06.234377

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ce6238fc635e'
down_revision = 'be6c2fbdf96f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_userprojectrole_project_id'), 'userprojectrole', ['project_id'], unique=False)
    op.create_index(op.f('ix_userprojectrole_role_id'), 'userprojectrole', ['role_id'], unique=False)
    op.create_index(op.f('ix_userprojectrole_user_id'), 'userprojectrole', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_userprojectrole_user_id'), table_name='userprojectrole')
    op.drop_index(op.f('ix_userprojectrole_role_id'), table_name='userprojectrole')
    op.drop_index(op.f('ix_userprojectrole_project_id'), table_name='userprojectrole')
    # ### end Alembic commands ###
