"""UP models 11/9.10h

Revision ID: dc57ccfaa307
Revises: bb5ff0d4e0be
Create Date: 2025-09-11 11:28:13.882305

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'dc57ccfaa307'
down_revision = 'bb5ff0d4e0be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
