"""UP models 22.07

Revision ID: e0cf886b4ed0
Revises: 41534ce97dcd
Create Date: 2025-07-22 10:01:20.784975

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e0cf886b4ed0'
down_revision = '41534ce97dcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ecopark', sa.Column('description_vi', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ecopark', sa.Column('description_en', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('projectlist', sa.Column('picture', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projectlist', 'picture')
    op.drop_column('ecopark', 'description_en')
    op.drop_column('ecopark', 'description_vi')
    # ### end Alembic commands ###
