"""UP models 26.7/15.40h

Revision ID: e5bf184bf0b0
Revises: 5bd6ae48ffcd
Create Date: 2025-07-26 15:51:02.261983

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e5bf184bf0b0'
down_revision = '5bd6ae48ffcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
