"""UP models 30/8.12h

Revision ID: e69bfa9b3f58
Revises: e871f2576a15
Create Date: 2025-08-30 11:21:31.692146

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e69bfa9b3f58'
down_revision = 'e871f2576a15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
