"""UP models 30/8.11h

Revision ID: e871f2576a15
Revises: 7a7d556bcaf1
Create Date: 2025-08-30 11:15:23.858843

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e871f2576a15'
down_revision = '7a7d556bcaf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
