"""UP models 24.7/12h

Revision ID: f1bbf0d4600a
Revises: 4fa6cd20d79f
Create Date: 2025-07-24 11:10:35.664901

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f1bbf0d4600a'
down_revision = '4fa6cd20d79f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
